# Generated by Django 4.2.2 on 2024-02-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=250)),
                ('Duration', models.IntegerField(default=0)),
                ('TotalLecture', models.IntegerField(default=0)),
                ('Category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.categorymodel')),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teachermodel')),
            ],
        ),
    ]
