# Generated by Django 4.2.2 on 2024-02-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_studentmodel_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
